http:
  debug_endpoints: true

input:
  oracledb_cdc:
    connection_string: oracle://system:YourPassword123@localhost:1521/XE
    stream_snapshot: false
    snapshot_max_batch_size: 500
    logminer:
      max_batch_size: 1000
      backoff_interval: 1s
    include:
      - TESTDB.USERS
      # - testdb.products
      # - testdb.cart
    batching:
      count: 5
      period: 100ms


output:
#   processors:
#     - benchmark:
#         interval: 1s
#         count_bytes: true
  stdout: {}
  # drop: {}
  # file:
  #   path: "./results.json" # No default (required)
  #   codec: lines

logger:
  level: DEBUG

metrics:
  prometheus:
    add_process_metrics: true
    add_go_metrics: true
