http:
  enabled: false

input:
  kafka:
    addresses: [ localhost:9092 ]
    topics: [ b_results ]
    client_id: c_client
    extract_tracing_map: 'root = meta()'

pipeline:
  processors:
    - bloblang: |
        root = this
        root.cities = this.CITIES.lowercase()

output:
  stdout: {}

tracer:
  jaeger:
    agent_address: 'localhost:6831'
    tags:
      pipeline: my_tracing_example
