input:
  type: broker
  broker:
    inputs:
      - type: kafka
        kafka:
          addresses:
          - localhost:9092
          client_id: benthos_kafka_input
          consumer_group: benthos_consumer_group
          topic: benthos_stream
          partition: 0
          start_from_oldest: true

      # Type ditto will copy the previous config and overwrite any new values.
      - type: ditto
        kafka:
          partition: 1
      # And can be used any number of times.
      - type: ditto
        kafka:
          partition: 2
output:
  type: stdout
