input:
  type: stdin
output:
  # Fanning out means every output will receive each message. If an output
  # blocks then all outputs will block also. The 'round_robin' pattern will only
  # send each message to one output, following them in order.
  type: broker
  broker:
    pattern: fan_out
    outputs:
      - type: kafka
        kafka:
          addresses:
          - localhost:9092
          client_id: benthos_kafka_output
          topic: benthos_stream
          timeout_ms: 5000
          ack_replicas: true
      - type: amqp
        amqp:
          uri: amqp://guest:guest@localhost:5672/
          exchange: benthos-exchange
          exchange_type: direct
          key: benthos-key
      - type: nats_stream
        nats_stream:
          cluster: nats://localhost:4222
          client_id: benthos_client
          subject: benthos_messages
