http:
  address: 0.0.0.0:4195
  read_timeout_ms: 5000
input:
  type: http_server
  http_server:
    address: localhost:8080
    path: /post
    timeout_ms: 5000
    cert_file: ""
    key_file: ""
output:
  type: http_client
  http_client:
    url: http://localhost:8081/post
    oauth:
      consumer_key: ""
      consumer_secret: ""
      access_token: ""
      access_token_secret: ""
      request_url: ""
      enabled: false
    timeout_ms: 5000
    retry_period_ms: 1000
    retries: 3
    skip_cert_verify: false

  # Alternatively, you can choose to output by hosting a server that consumers
  # connect to:
  http_server:
    address: localhost:8081
    path: /get
    timeout_ms: 5000
    cert_file: ""
    key_file: ""
