input:
  type: amqp
  amqp:
    uri: amqp://guest:guest@localhost:5672/
    exchange: benthos-exchange
    exchange_type: direct
    queue: benthos-queue
    key: benthos-key
    consumer_tag: benthos-consumer
    prefetch_count: 1
    prefetch_size: 0
output:
  type: amqp
  amqp:
    uri: amqp://guest:guest@localhost:5672/
    exchange: benthos-exchange
    exchange_type: direct
    key: benthos-key
