input:
  type: zmq4
  zmq4:
    addresses:
    - tcp://localhost:5555
    bind: false
    socket_type: PULL
    sub_filters: []
    high_water_mark: 0
    poll_timeout_ms: 5000
output:
  type: zmq4
  zmq4:
    addresses:
    - tcp://*:5556
    bind: true
    socket_type: PUSH
    high_water_mark: 0
