services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-15}
    restart: always
    command: ["-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pglogrepl}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-pglogrepl}
      POSTGRES_HOST_AUTH_METHOD: trust
    network_mode: "host"