input: 
  stdin: {}

pipeline:
  processors:
    - workflow:
        # meta_path: meta.workflow
        order: [ [ A ], [ B, C ], [ E ], [ D, F ] ]

        #       /--> B -------------|--> D
        #      /                   /
        # A --|          /--> E --|
        #      \--> C --|          \
        #                \----------|--> F
        
        branches:
          A:
            processors:
            #   - log:
            #       level: INFO
            #       message: STAGE A STARTED
              - sleep:
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE A FINISHED

          B:
            processors:
              # - log:
              #     level: INFO
              #     message: STAGE B STARTED
              - sleep: 
                  duration: "15s"
              - log:
                  level: INFO
                  message: STAGE B FINISHED

          C:
            processors:
              # - log:
              #     level: INFO
              #     message: STAGE C STARTED
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE C FINISHED

          D:
            processors:
              # - log:
              #     level: INFO
              #     message: STAGE D STARTED
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE D FINISHED

          # Stage E won't exec until B has finished even though there is 
          # no direct dependency on B.
          E: 
            processors:
              # - log:
              #     level: INFO
              #     message: STAGE E STARTED
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE E FINISHED

          F:
            processors:
              # - log:
              #     level: INFO
              #     message: STAGE F STARTED
              - sleep: 
                  duration: "3s"
              - log:
                  level: INFO
                  message: STAGE F FINISHED

output:
  stdout: {}